import { PastelColors } from '../src/config/Color';
import UUID from '../src/config/UUID';

export const Deck = {
  '7NCodht%}0': {
    general: {
      title: 'Formula Round 1',
      description: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      user: 'WUgzMNtDDAap5TkAXZbrPwF97Bu2',
      language: { term: 'Japanese', definition: 'Japanese' },
      num: 63,
      thumbnail: {
        uri: 'photo-1515705576963-95cad62945b6?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8bWlsa3klMjB3YXl8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: {
      'f2Tn8xG>': {
        term: 'あからさまなり(2)',
        definition: '①ちょっと (②急だ、突然だ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'A=+LL}%b': {
        term: 'あだなり(2)',
        definition: '①はかない ②浮気だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '2w-kD*RA': {
        term: 'かりそめなり(2)',
        definition: '①一時的だ ②いいかげんだ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '&3-TOzgJ': {
        term: 'おろかなり(2)',
        definition: '①いいかげんだ (②愚かだ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'd*e2C%)&': {
        term: 'なのめなり(2)',
        definition: '①いいかげんだ ②平凡だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'NK{81)9P': {
        term: 'なめげなり',
        definition: '①無礼だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      'e*173|Wh': {
        term: 'まめなり(2)',
        definition: '①誠実だ ②実用的だ、(本格的だ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      nOvA10Lh: {
        term: 'まめまめし(2)',
        definition: '①実用的だ ②真面目だ、(誠実だ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '%Bsu82qn': {
        term: 'あさまし(2)',
        definition: '①(意外なことに)驚きあきれたことだ (②情けない、興ざめだ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'TlJhtL)R': {
        term: 'おどろおどろし(2)',
        definition: '①大げさだ ②気味が悪い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '&C5S7uh5': {
        term: 'めざまし(2)',
        definition: '①興ざめだ、気にくわない ②思いのほか立派だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'h5m(8V=C': {
        term: 'すさまじ(2)',
        definition: '①興ざめだ ②薄情だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      qRQzWEqP: {
        term: 'すごし(2)',
        definition: '①ものさびしい、ぞっとする ②ぞっとするほどすばらしい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'UwZ1}WVv': {
        term: 'やさし(3)',
        definition: '①つらい、耐え難い ②優美だ (③けなげだ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'Sz71V2D}': {
        term: 'すきずきし(2)',
        definition: '①風情がある ②好色めいている',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '0)yQY(>)': {
        term: 'おもしろし',
        definition: '①風情がある、趣深い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      '78)&p+T:': {
        term: 'あはれなり(3)',
        definition: '①しみじみと...だ ②気の毒だ ③趣深い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '1w:cjv2&': {
        term: 'をかし(3)',
        definition: '①趣がある ②かわいい ③妙だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '<K2M82a1': {
        term: 'かなし(2)',
        definition: '①かわいい、(愛しい) ②悲しい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'h=tu>Y:T': {
        term: 'うつくし(2)',
        definition: '①かわいい ②きれいだ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '}25^hF}k': {
        term: 'ありがたし(2)(漢)',
        definition: '【有難し】 ①めったにない ②(めったにないほど)すばらしい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'x6iOu!li': {
        term: 'かたし(2)(漢)',
        definition: '【難し】 ①難しい ②めったにない',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      OW6XOXCx: {
        term: 'めづらし(2)',
        definition: '①すばらしい (②愛らしい)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '-|og-yYI': {
        term: 'あたらし(2)(漢)',
        definition: '【惜し・新し】 ①惜しい ②新しい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      llPJgg3k: {
        term: 'あやし(3)',
        definition: '①みすぼらしい ②不思議だ ③身分が低い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'qm>Q-ibY': {
        term: 'いやし①',
        definition: '①身分が低い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      YbB02u0x: {
        term: 'はづかし(2)',
        definition: '①立派だ ②恥ずかしい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'XCMh%~01': {
        term: 'まばゆし(2)',
        definition: '①恥ずかしい ②まぶしい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '{VSy38^1': {
        term: 'ねたし(2)',
        definition: '①憎らしい ②ねたましいほどすばらしい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'H+p4DmZf': {
        term: 'にくし(3)',
        definition: '①無愛想だ ②憎らしい ③ぶかっこうだ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '4sF+tFZ:': {
        term: 'ふつつかなり(2)(漢)',
        definition: '【不束なり】 ①ぶかっこうだ ②どっしりとしている',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'LoEE^CfY': {
        term: 'あながち(2)',
        definition: '①強引だ、一途だ ②必ずしも(打消)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      ':J{Qs!Gw': {
        term: 'かたくななり(2)',
        definition: '①頑固だ、偏屈だ ②みっともない、(見苦しい)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      E1C8Iheb: {
        term: 'あつし(漢)',
        definition: '【篤し】 ①病気が重い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      ':A1Tc|DY': {
        term: 'なやまし(2)',
        definition: '①気分が悪い ②病気がちだ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'ht(6z{(b': {
        term: 'いたはし(2)',
        definition: '①気の毒だ ②愛しい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'um5l!R)r': {
        term: 'いとほし(2)',
        definition: '①気の毒だ ②愛しい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'TrQpqLO|': {
        term: 'ふびんなり(2)(漢)',
        definition: '【不便なり・不憫なり】 ①不都合だ ②気の毒だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'TyXy~wac': {
        term: 'うとし',
        definition: '①疎遠だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      'r:Y*IGN5': {
        term: 'うとまし(2)',
        definition: '①気味が悪い ②嫌だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      XmksnZFw: {
        term: 'なつかし(2)',
        definition: '①親しみやすい (②心が引かれる)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'NvQ7^&UJ': {
        term: 'むつまし',
        definition: '①親しい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      v7RHazIq: {
        term: 'うるはし(2)',
        definition: '①整って美しい ②筋が通っている',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'dI~*68bd': {
        term: 'うるさし(2)',
        definition: '①賢い、立派だ ②わずらわしい、(いやみだ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'a8TiJtO&': {
        term: 'ことわりなり',
        definition: '①もっともだ、当然だ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      EMsnXKGQ: {
        term: 'いたづらなり(2)',
        definition: '①退屈だ、(暇だ) ②役に立たない、(無駄だ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'JRHA<kIW': {
        term: 'さうざうし',
        definition: '①さびしい、(物足りない)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      'SpP}!Oo<': {
        term: 'ただなり(2)',
        definition: '①むなしい ②何でもない、(普通だ)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'F}{L3~gX': {
        term: 'そらなり(2)(漢)',
        definition: '【空なり】 ①うつろだ ②いいかげんだ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'OotCS-%<': {
        term: 'さかし(2)',
        definition: '①利口ぶっている ②賢い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '3>&I>y)S': {
        term: 'かしこし(2)',
        definition: '①恐れ多い ②すぐれている',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'F3oVXHE+': {
        term: 'くるし',
        definition: '①差し障りがある',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      fw9eRcrB: {
        term: 'つつまし(2)',
        definition: '①遠慮される (②気恥ずかしい)',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      d1E8AVPI: {
        term: 'いたし(2)',
        definition: '①はなはだしい ②すばらしい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'rsB:3B0K': {
        term: 'めでたし',
        definition: '①すばらしい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      X6pnXc7l: {
        term: 'わびし(2)',
        definition: '①さびしい ②つらい',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'LC|7o=Ek': {
        term: 'つらし(2)',
        definition: '①薄情だ ②耐え難い',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      'hiiAHR|&': {
        term: 'すくよかなり(2)',
        definition: '①しっかりしている ②そっけない',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      '|:2CMAVs': {
        term: 'うしろめたし',
        definition: '①気がかりだ',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      'w{Lwgd:)': {
        term: 'やすし(2)(漢)',
        definition: '【安し・易し】 ①心が穏やかだ ②簡単である',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      Xd2xjNfR: {
        term: 'はかばかし(2)',
        definition: '①しっかりしている ②はっきりしている',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],

      },
      sJn8zPa8: {
        term: 'さすがなり',
        definition: '①とはいっても、そうもいかない',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
      '(yc+)qE|': {
        term: 'さらなり',
        definition: '①言うまでもない',
        exampleT: [],
        exampleD: [],
        synonym: [],
        antonym: [],
        prefix: [],
        suffix: [],
        cf: [],
      },
    },
  },
  /* '-BiGIisZb*': {
    general: {
      title: 'Test Deck 2',
      description: '',
      user: 'KgZLhZvgTiTSYJ7VBFbfutjjtUE2',
      language: { term: 'French', definition: 'Japanese' },
      num: 3,
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: {
      ypjkhApD: {
        term: 'increase',
        definition: ['増える', '～を増やす'],
        exampleT: ['the number increased'],
        exampleD: ['数が増える'],
        synonym: ['grow', 'rise'],
        antonym: ['decrease', 'diminish', 'shrink'],
        prefix: ['in'],
        suffix: ['crease'],
        cf: [],
      },
      sFlEIDaB: {
        term: 'expect',
        definition: ['～を予期する', '期待する', '予想する'],
        exampleT: ['expect no mercy'],
        exampleD: ['慈悲など求めない'],
        synonym: ['anticipate', 'predict', 'foresee', 'envision'],
        antonym: ['regret'],
        prefix: [],
        suffix: [],
        cf: [],
      },
      'PfRg:zR{': {
        term: 'consider',
        definition: ['～考慮する'],
        exampleT: ['all things considered'],
        exampleD: ['全ての事象を考慮した'],
        synonym: ['comtemplate', 'review'],
        antonym: ['ignore'],
        prefix: [],
        suffix: [],
        cf: [],
      },
    },
  }, */
  /*
  rUiKQdnLb9: {
    general: {
      title: 'Test Deck 3',
      description: '',
      user: 'WUgzMNtDDAap5TkAXZbrPwF97Bu2',
      language: { term: 'Chinese', definition: 'Japanese' },
      num: 4,
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: {
      wdPx0JnA: {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      'Z2%FYcP(': {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      Ub3wlJAr: {
        term: 'follow',
        definition: ['～（の後）に続く'],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        cf: ['escort', 'attend'],
      },
      TzyEbrTc: {
        term: 'consider',
        definition: ['～考慮する'],
        exampleT: ['all things considered'],
        exampleD: ['全ての事象を考慮した'],
        synonym: ['comtemplate', 'review'],
        antonym: ['ignore'],
        prefix: [],
        suffix: [],
        cf: [],
      },
    },
  },
  'xn>EfhY:2*': {
    general: {
      title: 'Test Deck 4',
      description: '',
      user: 'KgZLhZvgTiTSYJ7VBFbfutjjtUE2',
      language: { term: 'Spanish', definition: 'Japanese' },
      num: 3,
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: {
      MdmRNj0Y: {
        term: 'increase',
        definition: ['増える', '～を増やす'],
        exampleT: ['the number increased', 'increse drastically'],
        exampleD: ['数が増える', '劇的に増える'],
        synonym: ['grow', 'rise'],
        antonym: ['decrease', 'diminish', 'shrink'],
        prefix: ['in'],
        suffix: ['crease'],
        cf: [],
      },
      '5::oT=-v': {
        term: 'expect',
        definition: ['～を予期する', '期待する', '予想する'],
        exampleT: ['expect no mercy'],
        exampleD: ['慈悲など求めない'],
        synonym: ['anticipate', 'predict', 'foresee', 'envision'],
        antonym: ['regret'],
        prefix: [],
        suffix: [],
        cf: [],
      },
      'qIDjbgc-': {
        term: 'hypocrite',
        definition: ['偽善者'],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        cf: [],
      },
    },
  },
  'Q38xR=rnKc': {
    general: {
      title: 'Test Deck 5',
      description: '',
      user: 'WUgzMNtDDAap5TkAXZbrPwF97Bu2',
      language: { term: 'Korean', definition: 'Japanese' },
      num: 4,
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: {
      'qy%nQmid': {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      '>pA|x-V<': {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      lnz24x4C: {
        term: 'follow',
        definition: ['～（の後）に続く'],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        cf: ['escort', 'attend'],
      },
      '6:LSsg9s': {
        term: 'consider',
        definition: ['～考慮する'],
        exampleT: ['all things considered'],
        exampleD: ['全ての事象を考慮した'],
        synonym: ['comtemplate', 'review'],
        antonym: ['ignore'],
        prefix: [],
        suffix: [],
        cf: [],
      },
    },
  }, */
};

export const User = {
  // KgZLhZvgTiTSYJ7VBFbfutjjtUE2: {
  //   name: 'Sumio',
  //   icon: { uri: 'https://spring-js.com/wp-content/uploads/2017/06/01-1.jpg' },
  // },
  // WUgzMNtDDAap5TkAXZbrPwF97Bu2: {
  //   name: 'Vocabon',
  //   icon: { color: PastelColors[UUID.getRandom({ max: PastelColors.length })] },
  // },
};

export const Account = {
  general: {
    email: 'vocabon.team@gmail.com',
    password: 'bossbaby0121',
    name: 'Vocabon',
    userID: 'WUgzMNtDDAap5TkAXZbrPwF97Bu2',
  },
  content: { // 履歴
    '7NCodht%}0': { // deckID
      marks: {
        'f2Tn8xG>': [0, 1, 2, 3],
        'A=+LL}%b': [],
        '2w-kD*RA': [0, 4, 5],
        '&3-TOzgJ': [],
        'd*e2C%)&': [0, 4],
        'NK{81)9P': [1, 2, 3, 6, 7],
        'e*173|Wh': [4, 5],
        nOvA10Lh: [2, 3],
        '%Bsu82qn': [0, 1, 2, 3],
        'TlJhtL)R': [7],
        '&C5S7uh5': [],
        'h5m(8V=C': [1],
        qRQzWEqP: [5, 6],
        'UwZ1}WVv': [5],
        'Sz71V2D}': [0],
        '0)yQY(>)': [7],
        '78)&p+T:': [1, 6, 7],
        '1w:cjv2&': [0, 5],
        '<K2M82a1': [0, 1],
        'h=tu>Y:T': [],
        '}25^hF}k': [0],
        'x6iOu!li': [],
        OW6XOXCx: [5],
        '-|og-yYI': [],
        llPJgg3k: [6],
        'qm>Q-ibY': [],
        YbB02u0x: [0],
        'XCMh%~01': [],
        '{VSy38^1': [1],
        'H+p4DmZf': [6],
        '4sF+tFZ:': [],
        'LoEE^CfY': [],
        ':J{Qs!Gw': [5],
        E1C8Iheb: [1],
        ':A1Tc|DY': [],
        'ht(6z{(b': [],
        'um5l!R)r': [7],
        'TrQpqLO|': [6],
        'TyXy~wac': [5],
        'r:Y*IGN5': [2, 3, 4],
        XmksnZFw: [2, 3, 5],
        'NvQ7^&UJ': [2, 3],
        v7RHazIq: [],
        'dI~*68bd': [1, 4],
        'a8TiJtO&': [1],
        EMsnXKGQ: [2, 3],
        'JRHA<kIW': [5],
        'SpP}!Oo<': [6],
        'F}{L3~gX': [],
        'OotCS-%<': [],
        '3>&I>y)S': [7],
        'F3oVXHE+': [],
        fw9eRcrB: [5],
        d1E8AVPI: [1, 6],
        'rsB:3B0K': [],
        X6pnXc7l: [2, 3, 6],
        'LC|7o=Ek': [],
        'hiiAHR|&': [],
        '|:2CMAVs': [0],
        'w{Lwgd:)': [5, 7],
        Xd2xjNfR: [0, 2, 3],
        sJn8zPa8: [1, 2, 3, 6],
        '(yc+)qE|': [7],
      },
      play: [
        20201004,
        20201111,
        20201114,
        20201118,
        20201228,
        20201230,
        20201231,
        20210103,
      ],
      bookmark: false,
    },
    '-BiGIisZb*': {
      marks: {
        ypjkhApD: [0, 3, 4],
        sFlEIDaB: [2, 4],
        'PfRg:zR{': [0, 1],
      },
      play: [
        20201024,
        20201114,
        20201218,
        20201221,
        20210107,
      ],
      bookmark: true,
    },
    rUiKQdnLb9: {
      marks: {
        wdPx0JnA: [1, 4, 8],
        'Z2%FYcP(': [3, 4, 5, 6, 7, 8],
        Ub3wlJAr: [8],
        TzyEbrTc: [5, 8],
      },
      play: [
        20201007,
        20201011,
        20201024,
        20201109,
        20201119,
        20201128,
        20201206,
        20201222,
        20210104,
      ],
      bookmark: true,
    },
    'xn>EfhY:2*': {
      marks: {
        MdmRNj0Y: [2, 4, 8, 9],
        '5::oT=-v': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'qIDjbgc-': [3, 4, 7, 10],
      },
      play: [
        20201007,
        20201019,
        20201031,
        20201101,
        20201110,
        20201120,
        20201201,
        20201211,
        20201222,
        20210101,
        20210108,
      ],
      bookmark: true,
    },
    // 'Q38xR=rnKc': {
    //   marks: {
    //     'qy%nQmid': 1,
    //     '>pA|x-V<': 18,
    //     lnz24x4C: 9,
    //     '6:LSsg9s': 4,
    //   },
    //   latest: ['>pA|x-V<', '6:LSsg9s'],
    //   bookmark: false,
    // },
  },
};

export default { Deck, User, Account };
