export const Deck = {
  '7NCodht%}0': {
    general: {
      title: 'Test Deck 1',
      language: { term: 'English', definition: 'Japanese' },
      thumbnail: {
        uri: 'photo-1515705576963-95cad62945b6?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8bWlsa3klMjB3YXl8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: [
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      }, {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      }, {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      }, {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      }, {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },

      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
    ],
  },
  '-BiGIisZb*': {
    general: {
      title: 'Test Deck 2',
      language: { term: 'French', definition: 'Japanese' },
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: [
      {
        term: 'increase',
        definition: ['増える', '～を増やす'],
        synonym: ['grow', 'rise'],
        antonym: ['decrease', 'diminish', 'shrink'],
        prefix: ['in'],
        suffix: ['crease'],
        exampleT: ['the number increased'],
        exampleD: ['数が増える'],
        cf: [],
      },
      {
        term: 'expect',
        definition: ['～を予期する', '期待する', '予想する'],
        synonym: ['anticipate', 'predict', 'foresee', 'envision'],
        antonym: ['regret'],
        prefix: [],
        suffix: [],
        exampleT: ['expect no mercy'],
        exampleD: ['慈悲など求めない'],
        cf: [],
      },
      {
        term: 'consider',
        definition: ['～考慮する'],
        synonym: ['comtemplate', 'review'],
        antonym: ['ignore'],
        prefix: [],
        suffix: [],
        exampleT: ['all things considered'],
        exampleD: ['全ての事象を考慮した'],
        cf: [],
      },
    ],
  },
  rUiKQdnLb9: {
    general: {
      title: 'Test Deck 3',
      language: { term: 'Chinese', definition: 'Japanese' },
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: [
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'consider',
        definition: ['～考慮する'],
        synonym: ['comtemplate', 'review'],
        antonym: ['ignore'],
        prefix: [],
        suffix: [],
        exampleT: ['all things considered'],
        exampleD: ['全ての事象を考慮した'],
        cf: [],
      },
    ],
  },
  'xn>EfhY:2*': {
    general: {
      title: 'Test Deck 4',
      language: { term: 'Spanish', definition: 'Japanese' },
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: [
      {
        term: 'increase',
        definition: ['増える', '～を増やす'],
        synonym: ['grow', 'rise'],
        antonym: ['decrease', 'diminish', 'shrink'],
        prefix: ['in'],
        suffix: ['crease'],
        exampleT: ['the number increased'],
        exampleD: ['数が増える'],
        cf: [],
      },
      {
        term: 'expect',
        definition: ['～を予期する', '期待する', '予想する'],
        synonym: ['anticipate', 'predict', 'foresee', 'envision'],
        antonym: ['regret'],
        prefix: [],
        suffix: [],
        exampleT: ['expect no mercy'],
        exampleD: ['慈悲など求めない'],
        cf: [],
      },
      {
        term: 'hypocrite',
        definition: ['偽善者'],
        synonym: [],
        antonym: ['virtue'],
        prefix: [],
        suffix: [],
        exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
        exampleD: ['偽善者は善人の真似をする'],
        cf: [],
      },
    ],
  },
  'Q38xR=rnKc': {
    general: {
      title: 'Test Deck 5',
      language: { term: 'Korean', definition: 'Japanese' },
      thumbnail: {
        uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
        user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
      },
    },
    content: [
      {
        term: 'apple',
        definition: ['リンゴ', 'アップル'],
        synonym: [],
        antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
        prefix: [],
        suffix: [],
        exampleT: ['I hate Apple'],
        exampleD: ['私はアップル社が嫌いです'],
        cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
      },
      {
        term: 'hippopotomonstrosesquipedaliophobia',
        definition: ['長い単語恐怖症'],
        synonym: [],
        antonym: ['short tale lover'],
        prefix: [],
        suffix: ['phobia'],
        exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
        exampleD: ['長い単語恐怖症にさらされている'],
        cf: ['neophobia', 'technophobia', 'anthropophobia'],
      },
      {
        term: 'follow',
        definition: ['～（の後）に続く'],
        synonym: ['come after', 'go after', 'pursue'],
        antonym: ['lead', 'flout'],
        prefix: [],
        suffix: [],
        exampleT: ['Follow me home if you dare to.'],
        exampleD: ['あなたは彼に従うべきである'],
        cf: ['escort', 'attend'],
      },
      {
        term: 'consider',
        definition: ['～考慮する'],
        synonym: ['comtemplate', 'review'],
        antonym: ['ignore'],
        prefix: [],
        suffix: [],
        exampleT: ['all things considered'],
        exampleD: ['全ての事象を考慮した'],
        cf: [],
      },
    ],
  },
};

export const User = {
  KgZLhZvgTiTSYJ7VBFbfutjjtUE2: {
  },
  WUgzMNtDDAap5TkAXZbrPwF97Bu2: {

  },
};

export default {
  Deck,
};
