const langs = [
  { value: 0x0001, tag: 'ar', name: 'Arabic' },
  { value: 0x0002, tag: 'bg', name: 'Bulgarian' },
  { value: 0x0003, tag: 'ca', name: 'Catalan' },
  { value: 0x0004, tag: 'zh-Hans', name: 'Chinese, Han (Simplified variant)' },
  { value: 0x0005, tag: 'cs', name: 'Czech' },
  { value: 0x0006, tag: 'da', name: 'Danish' },
  { value: 0x0007, tag: 'de', name: 'German' },
  { value: 0x0008, tag: 'el', name: 'Modern Greek (1453 and later)' },
  { value: 0x0009, tag: 'en', name: 'English' },
  { value: 0x000a, tag: 'es', name: 'Spanish' },
  { value: 0x000b, tag: 'fi', name: 'Finnish' },
  { value: 0x000c, tag: 'fr', name: 'French' },
  { value: 0x000d, tag: 'he', name: 'Hebrew' },
  { value: 0x000e, tag: 'hu', name: 'Hungarian' },
  { value: 0x000f, tag: 'is', name: 'Icelandic' },
  { value: 0x0010, tag: 'it', name: 'Italian' },
  { value: 0x0011, tag: 'ja', name: 'Japanese' },
  { value: 0x0012, tag: 'ko', name: 'Korean' },
  { value: 0x0013, tag: 'nl', name: 'Dutch' },
  { value: 0x0014, tag: 'no', name: 'Norwegian' },
  { value: 0x0015, tag: 'pl', name: 'Polish' },
  { value: 0x0016, tag: 'pt', name: 'Portuguese' },
  { value: 0x0017, tag: 'rm', name: 'Romansh' },
  { value: 0x0018, tag: 'ro', name: 'Romanian' },
  { value: 0x0019, tag: 'ru', name: 'Russian' },
  { value: 0x001a, tag: 'hr', name: 'Croatian' },
  { value: 0x001b, tag: 'sk', name: 'Slovak' },
  { value: 0x001c, tag: 'sq', name: 'Albanian' },
  { value: 0x001d, tag: 'sv', name: 'Swedish' },
  { value: 0x001e, tag: 'th', name: 'Thai' },
  { value: 0x001f, tag: 'tr', name: 'Turkish' },
  { value: 0x0020, tag: 'ur', name: 'Urdu' },
  { value: 0x0021, tag: 'id', name: 'Indonesian' },
  { value: 0x0022, tag: 'uk', name: 'Ukrainian' },
  { value: 0x0023, tag: 'be', name: 'Belarusian' },
  { value: 0x0024, tag: 'sl', name: 'Slovenian' },
  { value: 0x0025, tag: 'et', name: 'Estonian' },
  { value: 0x0026, tag: 'lv', name: 'Latvian' },
  { value: 0x0027, tag: 'lt', name: 'Lithuanian' },
  { value: 0x0028, tag: 'tg', name: 'Tajik' },
  { value: 0x0029, tag: 'fa', name: 'Persian' },
  { value: 0x002a, tag: 'vi', name: 'Vietnamese' },
  { value: 0x002b, tag: 'hy', name: 'Armenian' },
  { value: 0x002c, tag: 'az', name: 'Azerbaijani' },
  { value: 0x002d, tag: 'eu', name: 'Basque' },
  { value: 0x002e, tag: 'hsb', name: 'Upper Sorbian' },
  { value: 0x002f, tag: 'mk', name: 'Macedonian' },
  { value: 0x0032, tag: 'tn', name: 'Tswana' },
  { value: 0x0034, tag: 'xh', name: 'Xhosa' },
  { value: 0x0035, tag: 'zu', name: 'Zulu' },
  { value: 0x0036, tag: 'af', name: 'Afrikaans' },
  { value: 0x0037, tag: 'ka', name: 'Georgian' },
  { value: 0x0038, tag: 'fo', name: 'Faroese' },
  { value: 0x0039, tag: 'hi', name: 'Hindi' },
  { value: 0x003a, tag: 'mt', name: 'Maltese' },
  { value: 0x003b, tag: 'se', name: 'Northern Sami' },
  { value: 0x003c, tag: 'ga', name: 'Irish' },
  { value: 0x003e, tag: 'ms', name: 'Malay (macrolanguage)' },
  { value: 0x003f, tag: 'kk', name: 'Kazakh' },
  { value: 0x0040, tag: 'ky', name: 'Kirghiz' },
  { value: 0x0041, tag: 'sw', name: 'Swahili (macrolanguage)' },
  { value: 0x0042, tag: 'tk', name: 'Turkmen' },
  { value: 0x0043, tag: 'uz', name: 'Uzbek' },
  { value: 0x0044, tag: 'tt', name: 'Tatar' },
  { value: 0x0045, tag: 'bn', name: 'Bengali' },
  { value: 0x0046, tag: 'pa', name: 'Panjabi' },
  { value: 0x0047, tag: 'gu', name: 'Gujarati' },
  { value: 0x0048, tag: 'or', name: 'Oriya' },
  { value: 0x0049, tag: 'ta', name: 'Tamil' },
  { value: 0x004a, tag: 'te', name: 'Telugu' },
  { value: 0x004b, tag: 'kn', name: 'Kannada' },
  { value: 0x004c, tag: 'ml', name: 'Malayalam' },
  { value: 0x004d, tag: 'as', name: 'Assamese' },
  { value: 0x004e, tag: 'mr', name: 'Marathi' },
  { value: 0x004f, tag: 'sa', name: 'Sanskrit' },
  { value: 0x0050, tag: 'mn', name: 'Mongolian' },
  { value: 0x0051, tag: 'bo', name: 'Tibetan' },
  { value: 0x0052, tag: 'cy', name: 'Welsh' },
  { value: 0x0053, tag: 'km', name: 'Central Khmer' },
  { value: 0x0054, tag: 'lo', name: 'Lao' },
  { value: 0x0056, tag: 'gl', name: 'Galician' },
  { value: 0x0057, tag: 'kok', name: 'Konkani (macrolanguage)' },
  { value: 0x005a, tag: 'syr', name: 'Syriac' },
  { value: 0x005b, tag: 'si', name: 'Sinhala' },
  { value: 0x005d, tag: 'iu', name: 'Inuktitut' },
  { value: 0x005e, tag: 'am', name: 'Amharic' },
  { value: 0x005f, tag: 'tzm', name: 'Central Atlas Tamazight' },
  { value: 0x0061, tag: 'ne', name: 'Nepali' },
  { value: 0x0062, tag: 'fy', name: 'Western Frisian' },
  { value: 0x0063, tag: 'ps', name: 'Pushto' },
  { value: 0x0064, tag: 'fil', name: 'Filipino' },
  { value: 0x0065, tag: 'dv', name: 'Dhivehi' },
  { value: 0x0068, tag: 'ha', name: 'Hausa' },
  { value: 0x006a, tag: 'yo', name: 'Yoruba' },
  { value: 0x006b, tag: 'quz', name: 'Cusco Quechua' },
  { value: 0x006c, tag: 'nso', name: 'Pedi' },
  { value: 0x006d, tag: 'ba', name: 'Bashkir' },
  { value: 0x006e, tag: 'lb', name: 'Luxembourgish' },
  { value: 0x006f, tag: 'kl', name: 'Kalaallisut' },
  { value: 0x0070, tag: 'ig', name: 'Igbo' },
  { value: 0x0078, tag: 'ii', name: 'Sichuan Yi' },
  { value: 0x007a, tag: 'arn', name: 'Mapudungun' },
  { value: 0x007c, tag: 'moh', name: 'Mohawk' },
  { value: 0x007e, tag: 'br', name: 'Breton' },
  { value: 0x0080, tag: 'ug', name: 'Uighur' },
  { value: 0x0081, tag: 'mi', name: 'Maori' },
  { value: 0x0082, tag: 'oc', name: 'Occitan (post 1500)' },
  { value: 0x0083, tag: 'co', name: 'Corsican' },
  { value: 0x0084, tag: 'gsw', name: 'Swiss German' },
  { value: 0x0085, tag: 'sah', name: 'Yakut' },
  { value: 0x0086, tag: 'qut', name: 'Guatemala' },
  { value: 0x0087, tag: 'rw', name: 'Kinyarwanda' },
  { value: 0x0088, tag: 'wo', name: 'Wolof' },
  { value: 0x008c, tag: 'prs', name: 'Dari' },
  { value: 0x0091, tag: 'gd', name: 'Scottish Gaelic' },
  { value: 0x0401, tag: 'ar-SA', name: 'Arabic, Saudi Arabia' },
  { value: 0x0402, tag: 'bg-BG', name: 'Bulgarian, Bulgaria' },
  { value: 0x0403, tag: 'ca-ES', name: 'Catalan, Spain' },
  { value: 0x0404, tag: 'zh-TW', name: 'Chinese, Taiwan, Province of China' },
  { value: 0x0405, tag: 'cs-CZ', name: 'Czech, Czech Republic' },
  { value: 0x0406, tag: 'da-DK', name: 'Danish, Denmark' },
  { value: 0x0407, tag: 'de-DE', name: 'German, Germany' },
  { value: 0x0408, tag: 'el-GR', name: 'Modern Greek (1453-), Greece' },
  { value: 0x0409, tag: 'en-US', name: 'English, United States' },
  { value: 0x040a, tag: 'es-ES_tradnl', name: 'Spanish' },
  { value: 0x040b, tag: 'fi-FI', name: 'Finnish, Finland' },
  { value: 0x040c, tag: 'fr-FR', name: 'French, France' },
  { value: 0x040d, tag: 'he-IL', name: 'Hebrew, Israel' },
  { value: 0x040e, tag: 'hu-HU', name: 'Hungarian, Hungary' },
  { value: 0x040f, tag: 'is-IS', name: 'Icelandic, Iceland' },
  { value: 0x0410, tag: 'it-IT', name: 'Italian, Italy' },
  { value: 0x0411, tag: 'ja-JP', name: 'Japanese, Japan' },
  { value: 0x0412, tag: 'ko-KR', name: 'Korean, Republic of Korea' },
  { value: 0x0413, tag: 'nl-NL', name: 'Dutch, Netherlands' },
  { value: 0x0414, tag: 'nb-NO', name: 'Norwegian Bokmål, Norway' },
  { value: 0x0415, tag: 'pl-PL', name: 'Polish, Poland' },
  { value: 0x0416, tag: 'pt-BR', name: 'Portuguese, Brazil' },
  { value: 0x0417, tag: 'rm-CH', name: 'Romansh, Switzerland' },
  { value: 0x0418, tag: 'ro-RO', name: 'Romanian, Romania' },
  { value: 0x0419, tag: 'ru-RU', name: 'Russian, Russian Federation' },
  { value: 0x041a, tag: 'hr-HR', name: 'Croatian, Croatia' },
  { value: 0x041b, tag: 'sk-SK', name: 'Slovak, Slovakia' },
  { value: 0x041c, tag: 'sq-AL', name: 'Albanian, Albania' },
  { value: 0x041d, tag: 'sv-SE', name: 'Swedish, Sweden' },
  { value: 0x041e, tag: 'th-TH', name: 'Thai, Thailand' },
  { value: 0x041f, tag: 'tr-TR', name: 'Turkish, Turkey' },
  { value: 0x0420, tag: 'ur-PK', name: 'Urdu, Pakistan' },
  { value: 0x0421, tag: 'id-ID', name: 'Indonesian, Indonesia' },
  { value: 0x0422, tag: 'uk-UA', name: 'Ukrainian, Ukraine' },
  { value: 0x0423, tag: 'be-BY', name: 'Belarusian, Belarus' },
  { value: 0x0424, tag: 'sl-SI', name: 'Slovenian, Slovenia' },
  { value: 0x0425, tag: 'et-EE', name: 'Estonian, Estonia' },
  { value: 0x0426, tag: 'lv-LV', name: 'Latvian, Latvia' },
  { value: 0x0427, tag: 'lt-LT', name: 'Lithuanian, Lithuania' },
  { value: 0x0428, tag: 'tg-Cyrl-TJ', name: 'Tajik, Cyrillic, Tajikistan' },
  { value: 0x0429, tag: 'fa-IR', name: 'Persian, Islamic Republic of Iran' },
  { value: 0x042a, tag: 'vi-VN', name: 'Vietnamese, Viet Nam' },
  { value: 0x042b, tag: 'hy-AM', name: 'Armenian, Armenia' },
  { value: 0x042c, tag: 'az-Latn-AZ', name: 'Azerbaijani, Latin, Azerbaijan' },
  { value: 0x042d, tag: 'eu-ES', name: 'Basque, Spain' },
  { value: 0x042e, tag: 'wen-DE', name: 'Sorbian languages, Germany' },
  { value: 0x042f, tag: 'mk-MK', name: 'Macedonian, The Former Yugoslav Republic of Macedonia' },
  { value: 0x0430, tag: 'st-ZA', name: 'Southern Sotho, South Africa' },
  { value: 0x0431, tag: 'ts-ZA', name: 'Tsonga, South Africa' },
  { value: 0x0432, tag: 'tn-ZA', name: 'Tswana, South Africa' },
  { value: 0x0433, tag: 'ven-ZA', name: 'South Africa' },
  { value: 0x0434, tag: 'xh-ZA', name: 'Xhosa, South Africa' },
  { value: 0x0435, tag: 'zu-ZA', name: 'Zulu, South Africa' },
  { value: 0x0436, tag: 'af-ZA', name: 'Afrikaans, South Africa' },
  { value: 0x0437, tag: 'ka-GE', name: 'Georgian, Georgia' },
  { value: 0x0438, tag: 'fo-FO', name: 'Faroese, Faroe Islands' },
  { value: 0x0439, tag: 'hi-IN', name: 'Hindi, India' },
  { value: 0x043a, tag: 'mt-MT', name: 'Maltese, Malta' },
  { value: 0x043b, tag: 'se-NO', name: 'Northern Sami, Norway' },
  { value: 0x043e, tag: 'ms-MY', name: 'Malay (macrolanguage), Malaysia' },
  { value: 0x043f, tag: 'kk-KZ', name: 'Kazakh, Kazakhstan' },
  { value: 0x0440, tag: 'ky-KG', name: 'Kirghiz, Kyrgyzstan' },
  { value: 0x0441, tag: 'sw-KE', name: 'Swahili (macrolanguage), Kenya' },
  { value: 0x0442, tag: 'tk-TM', name: 'Turkmen, Turkmenistan' },
  { value: 0x0443, tag: 'uz-Latn-UZ', name: 'Uzbek, Latin, Uzbekistan' },
  { value: 0x0444, tag: 'tt-RU', name: 'Tatar, Russian Federation' },
  { value: 0x0445, tag: 'bn-IN', name: 'Bengali, India' },
  { value: 0x0446, tag: 'pa-IN', name: 'Panjabi, India' },
  { value: 0x0447, tag: 'gu-IN', name: 'Gujarati, India' },
  { value: 0x0448, tag: 'or-IN', name: 'Oriya, India' },
  { value: 0x0449, tag: 'ta-IN', name: 'Tamil, India' },
  { value: 0x044a, tag: 'te-IN', name: 'Telugu, India' },
  { value: 0x044b, tag: 'kn-IN', name: 'Kannada, India' },
  { value: 0x044c, tag: 'ml-IN', name: 'Malayalam, India' },
  { value: 0x044d, tag: 'as-IN', name: 'Assamese, India' },
  { value: 0x044e, tag: 'mr-IN', name: 'Marathi, India' },
  { value: 0x044f, tag: 'sa-IN', name: 'Sanskrit, India' },
  { value: 0x0450, tag: 'mn-MN', name: 'Mongolian, Mongolia' },
  { value: 0x0451, tag: 'bo-CN', name: 'Tibetan, China' },
  { value: 0x0452, tag: 'cy-GB', name: 'Welsh, United Kingdom' },
  { value: 0x0453, tag: 'km-KH', name: 'Central Khmer, Cambodia' },
  { value: 0x0454, tag: 'lo-LA', name: 'Lao, Lao People’s Democratic Republic' },
  { value: 0x0455, tag: 'my-MM', name: 'Burmese, Myanmar' },
  { value: 0x0456, tag: 'gl-ES', name: 'Galician, Spain' },
  { value: 0x0457, tag: 'kok-IN', name: 'Konkani (macrolanguage), India' },
  { value: 0x0458, tag: 'mni', name: 'Manipuri' },
  { value: 0x0459, tag: 'sd-IN', name: 'Sindhi, India' },
  { value: 0x045a, tag: 'syr-SY', name: 'Syriac, Syrian Arab Republic' },
  { value: 0x045b, tag: 'si-LK', name: 'Sinhala, Sri Lanka' },
  { value: 0x045c, tag: 'chr-US', name: 'Cherokee, United States' },
  { value: 0x045d, tag: 'iu-Cans-CA', name: 'Inuktitut, Unified Canadian Aboriginal Syllabics, Canada' },
  { value: 0x045e, tag: 'am-ET', name: 'Amharic, Ethiopia' },
  { value: 0x045f, tag: 'tmz', name: 'Tamanaku' },
  { value: 0x0461, tag: 'ne-NP', name: 'Nepali, Nepal' },
  { value: 0x0462, tag: 'fy-NL', name: 'Western Frisian, Netherlands' },
  { value: 0x0463, tag: 'ps-AF', name: 'Pushto, Afghanistan' },
  { value: 0x0464, tag: 'fil-PH', name: 'Filipino, Philippines' },
  { value: 0x0465, tag: 'dv-MV', name: 'Dhivehi, Maldives' },
  { value: 0x0466, tag: 'bin-NG', name: 'Bini, Nigeria' },
  { value: 0x0467, tag: 'fuv-NG', name: 'Nigerian Fulfulde, Nigeria' },
  { value: 0x0468, tag: 'ha-Latn-NG', name: 'Hausa, Latin, Nigeria' },
  { value: 0x0469, tag: 'ibb-NG', name: 'Ibibio, Nigeria' },
  { value: 0x046a, tag: 'yo-NG', name: 'Yoruba, Nigeria' },
  { value: 0x046b, tag: 'quz-BO', name: 'Cusco Quechua, Bolivia' },
  { value: 0x046c, tag: 'nso-ZA', name: 'Pedi, South Africa' },
  { value: 0x046d, tag: 'ba-RU', name: 'Bashkir, Russian Federation' },
  { value: 0x046e, tag: 'lb-LU', name: 'Luxembourgish, Luxembourg' },
  { value: 0x046f, tag: 'kl-GL', name: 'Kalaallisut, Greenland' },
  { value: 0x0470, tag: 'ig-NG', name: 'Igbo, Nigeria' },
  { value: 0x0471, tag: 'kr-NG', name: 'Kanuri, Nigeria' },
  { value: 0x0472, tag: 'gaz-ET', name: 'West Central Oromo, Ethiopia' },
  { value: 0x0473, tag: 'ti-ER', name: 'Tigrinya, Eritrea' },
  { value: 0x0474, tag: 'gn-PY', name: 'Guarani, Paraguay' },
  { value: 0x0475, tag: 'haw-US', name: 'Hawaiian, United States' },
  { value: 0x0477, tag: 'so-SO', name: 'Somali, Somalia' },
  { value: 0x0478, tag: 'ii-CN', name: 'Sichuan Yi, China' },
  { value: 0x0479, tag: 'pap-AN', name: 'Papiamento, Netherlands Antilles' },
  { value: 0x047a, tag: 'arn-CL', name: 'Mapudungun, Chile' },
  { value: 0x047c, tag: 'moh-CA', name: 'Mohawk, Canada' },
  { value: 0x047e, tag: 'br-FR', name: 'Breton, France' },
  { value: 0x0480, tag: 'ug-CN', name: 'Uighur, China' },
  { value: 0x0481, tag: 'mi-NZ', name: 'Maori, New Zealand' },
  { value: 0x0482, tag: 'oc-FR', name: 'Occitan (post 1500), France' },
  { value: 0x0483, tag: 'co-FR', name: 'Corsican, France' },
  { value: 0x0484, tag: 'gsw-FR', name: 'Swiss German, France' },
  { value: 0x0485, tag: 'sah-RU', name: 'Yakut, Russian Federation' },
  { value: 0x0486, tag: 'qut-GT', name: 'Guatemala' },
  { value: 0x0487, tag: 'rw-RW', name: 'Kinyarwanda, Rwanda' },
  { value: 0x0488, tag: 'wo-SN', name: 'Wolof, Senegal' },
  { value: 0x048c, tag: 'prs-AF', name: 'Dari, Afghanistan' },
  { value: 0x048d, tag: 'plt-MG', name: 'Plateau Malagasy, Madagascar' },
  { value: 0x0491, tag: 'gd-GB', name: 'Scottish Gaelic, United Kingdom' },
  { value: 0x0801, tag: 'ar-IQ', name: 'Arabic, Iraq' },
  { value: 0x0804, tag: 'zh-CN', name: 'Chinese, China' },
  { value: 0x0807, tag: 'de-CH', name: 'German, Switzerland' },
  { value: 0x0809, tag: 'en-GB', name: 'English, United Kingdom' },
  { value: 0x080a, tag: 'es-MX', name: 'Spanish, Mexico' },
  { value: 0x080c, tag: 'fr-BE', name: 'French, Belgium' },
  { value: 0x0810, tag: 'it-CH', name: 'Italian, Switzerland' },
  { value: 0x0813, tag: 'nl-BE', name: 'Dutch, Belgium' },
  { value: 0x0814, tag: 'nn-NO', name: 'Norwegian Nynorsk, Norway' },
  { value: 0x0816, tag: 'pt-PT', name: 'Portuguese, Portugal' },
  { value: 0x0818, tag: 'ro-MO', name: 'Romanian, Macao' },
  { value: 0x0819, tag: 'ru-MO', name: 'Russian, Macao' },
  { value: 0x081a, tag: 'sr-Latn-CS', name: 'Serbian, Latin, Serbia and Montenegro' },
  { value: 0x081d, tag: 'sv-FI', name: 'Swedish, Finland' },
  { value: 0x0820, tag: 'ur-IN', name: 'Urdu, India' },
  { value: 0x082c, tag: 'az-Cyrl-AZ', name: 'Azerbaijani, Cyrillic, Azerbaijan' },
  { value: 0x082e, tag: 'dsb-DE', name: 'Lower Sorbian, Germany' },
  { value: 0x083b, tag: 'se-SE', name: 'Northern Sami, Sweden' },
  { value: 0x083c, tag: 'ga-IE', name: 'Irish, Ireland' },
  { value: 0x083e, tag: 'ms-BN', name: 'Malay (macrolanguage), Brunei Darussalam' },
  { value: 0x0843, tag: 'uz-Cyrl-UZ', name: 'Uzbek, Cyrillic, Uzbekistan' },
  { value: 0x0845, tag: 'bn-BD', name: 'Bengali, Bangladesh' },
  { value: 0x0846, tag: 'pa-PK', name: 'Panjabi, Pakistan' },
  { value: 0x0850, tag: 'mn-Mong-CN', name: 'Mongolian, Mongolian, China' },
  { value: 0x0851, tag: 'bo-BT', name: 'Tibetan, Bhutan' },
  { value: 0x0859, tag: 'sd-PK', name: 'Sindhi, Pakistan' },
  { value: 0x085d, tag: 'iu-Latn-CA', name: 'Inuktitut, Latin, Canada' },
  { value: 0x085f, tag: 'tzm-Latn-DZ', name: 'Central Atlas Tamazight, Latin, Algeria' },
  { value: 0x0861, tag: 'ne-IN', name: 'Nepali, India' },
  { value: 0x086b, tag: 'quz-EC', name: 'Cusco Quechua, Ecuador' },
  { value: 0x0873, tag: 'ti-ET', name: 'Tigrinya, Ethiopia' },
  { value: 0x0c01, tag: 'ar-EG', name: 'Arabic, Egypt' },
  { value: 0x0c04, tag: 'zh-HK', name: 'Chinese, Hong Kong' },
  { value: 0x0c07, tag: 'de-AT', name: 'German, Austria' },
  { value: 0x0c09, tag: 'en-AU', name: 'English, Australia' },
  { value: 0x0c0a, tag: 'es-ES', name: 'Spanish, Spain' },
  { value: 0x0c0c, tag: 'fr-CA', name: 'French, Canada' },
  { value: 0x0c1a, tag: 'sr-Cyrl-CS', name: 'Serbian, Cyrillic, Serbia and Montenegro' },
  { value: 0x0c3b, tag: 'se-FI', name: 'Northern Sami, Finland' },
  { value: 0x0c5f, tag: 'tmz-MA', name: 'Tamanaku, Morocco' },
  { value: 0x0c6b, tag: 'quz-PE', name: 'Cusco Quechua, Peru' },
  { value: 0x1001, tag: 'ar-LY', name: 'Arabic, Libyan Arab Jamahiriya' },
  { value: 0x1004, tag: 'zh-SG', name: 'Chinese, Singapore' },
  { value: 0x1007, tag: 'de-LU', name: 'German, Luxembourg' },
  { value: 0x1009, tag: 'en-CA', name: 'English, Canada' },
  { value: 0x100a, tag: 'es-GT', name: 'Spanish, Guatemala' },
  { value: 0x100c, tag: 'fr-CH', name: 'French, Switzerland' },
  { value: 0x101a, tag: 'hr-BA', name: 'Croatian, Bosnia and Herzegovina' },
  { value: 0x103b, tag: 'smj-NO', name: 'Lule Sami, Norway' },
  { value: 0x1401, tag: 'ar-DZ', name: 'Arabic, Algeria' },
  { value: 0x1404, tag: 'zh-MO', name: 'Chinese, Macao' },
  { value: 0x1407, tag: 'de-LI', name: 'German, Liechtenstein' },
  { value: 0x1409, tag: 'en-NZ', name: 'English, New Zealand' },
  { value: 0x140a, tag: 'es-CR', name: 'Spanish, Costa Rica' },
  { value: 0x140c, tag: 'fr-LU', name: 'French, Luxembourg' },
  { value: 0x141a, tag: 'bs-Latn-BA', name: 'Bosnian, Latin, Bosnia and Herzegovina' },
  { value: 0x143b, tag: 'smj-SE', name: 'Lule Sami, Sweden' },
  { value: 0x1801, tag: 'ar-MA', name: 'Arabic, Morocco' },
  { value: 0x1809, tag: 'en-IE', name: 'English, Ireland' },
  { value: 0x180a, tag: 'es-PA', name: 'Spanish, Panama' },
  { value: 0x180c, tag: 'fr-MC', name: 'French, Monaco' },
  { value: 0x181a, tag: 'sr-Latn-BA', name: 'Serbian, Latin, Bosnia and Herzegovina' },
  { value: 0x183b, tag: 'sma-NO', name: 'Southern Sami, Norway' },
  { value: 0x1c01, tag: 'ar-TN', name: 'Arabic, Tunisia' },
  { value: 0x1c09, tag: 'en-ZA', name: 'English, South Africa' },
  { value: 0x1c0a, tag: 'es-DO', name: 'Spanish, Dominican Republic' },
  { value: 0x1c0c, tag: 'fr-West', name: 'French' },
  { value: 0x1c1a, tag: 'sr-Cyrl-BA', name: 'Serbian, Cyrillic, Bosnia and Herzegovina' },
  { value: 0x1c3b, tag: 'sma-SE', name: 'Southern Sami, Sweden' },
  { value: 0x2001, tag: 'ar-OM', name: 'Arabic, Oman' },
  { value: 0x2009, tag: 'en-JM', name: 'English, Jamaica' },
  { value: 0x200a, tag: 'es-VE', name: 'Spanish, Venezuela' },
  { value: 0x200c, tag: 'fr-RE', name: 'French, Réunion' },
  { value: 0x201a, tag: 'bs-Cyrl-BA', name: 'Bosnian, Cyrillic, Bosnia and Herzegovina' },
  { value: 0x203b, tag: 'sms-FI', name: 'Skolt Sami, Finland' },
  { value: 0x2401, tag: 'ar-YE', name: 'Arabic, Yemen' },
  { value: 0x2409, tag: 'en-CB', name: 'English' },
  { value: 0x240a, tag: 'es-CO', name: 'Spanish, Colombia' },
  { value: 0x240c, tag: 'fr-CG', name: 'French, Congo' },
  { value: 0x241a, tag: 'sr-Latn-RS', name: 'Serbian, Latin, Serbia' },
  { value: 0x243b, tag: 'smn-FI', name: 'Inari Sami, Finland' },
  { value: 0x2801, tag: 'ar-SY', name: 'Arabic, Syrian Arab Republic' },
  { value: 0x2809, tag: 'en-BZ', name: 'English, Belize' },
  { value: 0x280a, tag: 'es-PE', name: 'Spanish, Peru' },
  { value: 0x280c, tag: 'fr-SN', name: 'French, Senegal' },
  { value: 0x281a, tag: 'sr-Cyrl-RS', name: 'Serbian, Cyrillic, Serbia' },
  { value: 0x2c01, tag: 'ar-JO', name: 'Arabic, Jordan' },
  { value: 0x2c09, tag: 'en-TT', name: 'English, Trinidad and Tobago' },
  { value: 0x2c0a, tag: 'es-AR', name: 'Spanish, Argentina' },
  { value: 0x2c0c, tag: 'fr-CM', name: 'French, Cameroon' },
  { value: 0x2c1a, tag: 'sr-Latn-ME', name: 'Serbian, Latin, Montenegro' },
  { value: 0x3001, tag: 'ar-LB', name: 'Arabic, Lebanon' },
  { value: 0x3009, tag: 'en-ZW', name: 'English, Zimbabwe' },
  { value: 0x300a, tag: 'es-EC', name: 'Spanish, Ecuador' },
  { value: 0x300c, tag: 'fr-CI', name: 'French, Côte d’Ivoire' },
  { value: 0x301a, tag: 'sr-Cyrl-ME', name: 'Serbian, Cyrillic, Montenegro' },
  { value: 0x3401, tag: 'ar-KW', name: 'Arabic, Kuwait' },
  { value: 0x3409, tag: 'en-PH', name: 'English, Philippines' },
  { value: 0x340a, tag: 'es-CL', name: 'Spanish, Chile' },
  { value: 0x340c, tag: 'fr-ML', name: 'French, Mali' },
  { value: 0x3801, tag: 'ar-AE', name: 'Arabic, United Arab Emirates' },
  { value: 0x3809, tag: 'en-ID', name: 'English, Indonesia' },
  { value: 0x380a, tag: 'es-UY', name: 'Spanish, Uruguay' },
  { value: 0x380c, tag: 'fr-MA', name: 'French, Morocco' },
  { value: 0x3c01, tag: 'ar-BH', name: 'Arabic, Bahrain' },
  { value: 0x3c09, tag: 'en-HK', name: 'English, Hong Kong' },
  { value: 0x3c0a, tag: 'es-PY', name: 'Spanish, Paraguay' },
  { value: 0x3c0c, tag: 'fr-HT', name: 'French, Haiti' },
  { value: 0x4001, tag: 'ar-QA', name: 'Arabic, Qatar' },
  { value: 0x4009, tag: 'en-IN', name: 'English, India' },
  { value: 0x400a, tag: 'es-BO', name: 'Spanish, Bolivia' },
  { value: 0x4409, tag: 'en-MY', name: 'English, Malaysia' },
  { value: 0x440a, tag: 'es-SV', name: 'Spanish, El Salvador' },
  { value: 0x4809, tag: 'en-SG', name: 'English, Singapore' },
  { value: 0x480a, tag: 'es-HN', name: 'Spanish, Honduras' },
  { value: 0x4c0a, tag: 'es-NI', name: 'Spanish, Nicaragua' },
  { value: 0x500a, tag: 'es-PR', name: 'Spanish, Puerto Rico' },
  { value: 0x540a, tag: 'es-US', name: 'Spanish, United States' },
  { value: 0x641a, tag: 'bs-Cyrl', name: 'Bosnian, Cyrillic' },
  { value: 0x681a, tag: 'bs-Latn', name: 'Bosnian, Latin' },
  { value: 0x6c1a, tag: 'sr-Cyrl', name: 'Serbian, Cyrillic' },
  { value: 0x701a, tag: 'sr-Latn', name: 'Serbian, Latin' },
  { value: 0x703b, tag: 'smn', name: 'Inari Sami' },
  { value: 0x742c, tag: 'az-Cyrl', name: 'Azerbaijani, Cyrillic' },
  { value: 0x743b, tag: 'sms', name: 'Skolt Sami' },
  { value: 0x7804, tag: 'zh', name: 'Chinese' },
  { value: 0x7814, tag: 'nn', name: 'Norwegian Nynorsk' },
  { value: 0x781a, tag: 'bs', name: 'Bosnian' },
  { value: 0x782c, tag: 'az-Latn', name: 'Azerbaijani, Latin' },
  { value: 0x783b, tag: 'sma', name: 'Southern Sami' },
  { value: 0x7843, tag: 'uz-Cyrl', name: 'Uzbek, Cyrillic' },
  { value: 0x7850, tag: 'mn-Cyrl', name: 'Mongolian, Cyrillic' },
  { value: 0x785d, tag: 'iu-Cans', name: 'Inuktitut, Unified Canadian Aboriginal Syllabics' },
  { value: 0x7c04, tag: 'zh-Hant', name: 'Chinese, Han (Traditional variant)' },
  { value: 0x7c14, tag: 'nb', name: 'Norwegian Bokmål' },
  { value: 0x7c1a, tag: 'sr', name: 'Serbian' },
  { value: 0x7c28, tag: 'tg-Cyrl', name: 'Tajik, Cyrillic' },
  { value: 0x7c2e, tag: 'dsb', name: 'Lower Sorbian' },
  { value: 0x7c3b, tag: 'smj', name: 'Lule Sami' },
  { value: 0x7c43, tag: 'uz-Latn', name: 'Uzbek, Latin' },
  { value: 0x7c50, tag: 'mn-Mong', name: 'Mongolian, Mongolian' },
  { value: 0x7c5d, tag: 'iu-Latn', name: 'Inuktitut, Latin' },
  { value: 0x7c5f, tag: 'tzm-Latn', name: 'Central Atlas Tamazight, Latin' },
  { value: 0x7c68, tag: 'ha-Latn', name: 'Hausa, Latin' },
];

const majorLangTags = [
  'en', 'en-GB', 'zh', 'es', 'ar', 'hi', 'fr', 'de', 'ja', 'ru',
];
const majorLangs = langs.filter((lang) => majorLangTags.includes(lang.tag));

export { langs, majorLangs };

export default langs;
