// デッキの情報の変数を定義する所

import { atom } from 'recoil';
import decksContent from './DeckModule';

export const decksGeneral = atom({
  key: 'decksGeneral',
  default: {},
});

export { decksContent };

export default { decksContent, decksGeneral };

/*
decksContent = {
  '7NCodht%}0': {
    'Q!Am=KbD': {
      term: 'apple',
      definition: ['リンゴ', 'アップル'],
      synonym: [],
      antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
      prefix: [],
      suffix: [],
      exampleT: ['I hate Apple'],
      exampleD: ['私はアップル社が嫌いです'],
      cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
    },
    '3v8}weTF': {
      term: 'hippopotomonstrosesquipedaliophobia',
      definition: ['長い単語恐怖症'],
      synonym: [],
      antonym: ['short tale lover'],
      prefix: [],
      suffix: ['phobia'],
      exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
      exampleD: ['長い単語恐怖症にさらされている'],
      cf: ['neophobia', 'technophobia', 'anthropophobia'],
    },
    'wzntj)G9': {
      term: 'follow',
      definition: ['～（の後）に続く'],
      synonym: ['come after', 'go after', 'pursue'],
      antonym: ['lead', 'flout'],
      prefix: [],
      suffix: [],
      exampleT: ['Follow me home if you dare to.'],
      exampleD: ['あなたは彼に従うべきである'],
      cf: ['escort', 'attend'],
    },
    '(Oi48f(a': {
      term: 'hypocrite',
      definition: ['偽善者'],
      synonym: [],
      antonym: ['virtue'],
      prefix: [],
      suffix: [],
      exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
      exampleD: ['偽善者は善人の真似をする'],
      cf: [],
    },
  },
  '-BiGIisZb*': {
    ypjkhApD: {
      term: 'increase',
      definition: ['増える', '～を増やす'],
      synonym: ['grow', 'rise'],
      antonym: ['decrease', 'diminish', 'shrink'],
      prefix: ['in'],
      suffix: ['crease'],
      exampleT: ['the number increased'],
      exampleD: ['数が増える'],
      cf: [],
    },
    sFlEIDaB: {
      term: 'expect',
      definition: ['～を予期する', '期待する', '予想する'],
      synonym: ['anticipate', 'predict', 'foresee', 'envision'],
      antonym: ['regret'],
      prefix: [],
      suffix: [],
      exampleT: ['expect no mercy'],
      exampleD: ['慈悲など求めない'],
      cf: [],
    },
    'PfRg:zR{': {
      term: 'consider',
      definition: ['～考慮する'],
      synonym: ['comtemplate', 'review'],
      antonym: ['ignore'],
      prefix: [],
      suffix: [],
      exampleT: ['all things considered'],
      exampleD: ['全ての事象を考慮した'],
      cf: [],
    },
  },
  rUiKQdnLb9: {
    wdPx0JnA: {
      term: 'apple',
      definition: ['リンゴ', 'アップル'],
      synonym: [],
      antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
      prefix: [],
      suffix: [],
      exampleT: ['I hate Apple'],
      exampleD: ['私はアップル社が嫌いです'],
      cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
    },
    'Z2%FYcP(': {
      term: 'hippopotomonstrosesquipedaliophobia',
      definition: ['長い単語恐怖症'],
      synonym: [],
      antonym: ['short tale lover'],
      prefix: [],
      suffix: ['phobia'],
      exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
      exampleD: ['長い単語恐怖症にさらされている'],
      cf: ['neophobia', 'technophobia', 'anthropophobia'],
    },
    Ub3wlJAr: {
      term: 'follow',
      definition: ['～（の後）に続く'],
      synonym: ['come after', 'go after', 'pursue'],
      antonym: ['lead', 'flout'],
      prefix: [],
      suffix: [],
      exampleT: ['Follow me home if you dare to.'],
      exampleD: ['あなたは彼に従うべきである'],
      cf: ['escort', 'attend'],
    },
    TzyEbrTc: {
      term: 'consider',
      definition: ['～考慮する'],
      synonym: ['comtemplate', 'review'],
      antonym: ['ignore'],
      prefix: [],
      suffix: [],
      exampleT: ['all things considered'],
      exampleD: ['全ての事象を考慮した'],
      cf: [],
    },
  },
  'xn>EfhY:2*': {
    MdmRNj0Y: {
      term: 'increase',
      definition: ['増える', '～を増やす'],
      synonym: ['grow', 'rise'],
      antonym: ['decrease', 'diminish', 'shrink'],
      prefix: ['in'],
      suffix: ['crease'],
      exampleT: ['the number increased'],
      exampleD: ['数が増える'],
      cf: [],
    },
    '5::oT=-v': {
      term: 'expect',
      definition: ['～を予期する', '期待する', '予想する'],
      synonym: ['anticipate', 'predict', 'foresee', 'envision'],
      antonym: ['regret'],
      prefix: [],
      suffix: [],
      exampleT: ['expect no mercy'],
      exampleD: ['慈悲など求めない'],
      cf: [],
    },
    'qIDjbgc-': {
      term: 'hypocrite',
      definition: ['偽善者'],
      synonym: [],
      antonym: ['virtue'],
      prefix: [],
      suffix: [],
      exampleT: ['A hypocrite simulates virtue―counterfeits virtue.'],
      exampleD: ['偽善者は善人の真似をする'],
      cf: [],
    },
  },
  'Q38xR=rnKc': {
    'qy%nQmid': {
      term: 'apple',
      definition: ['リンゴ', 'アップル'],
      synonym: [],
      antonym: ['Microsoft', 'Google', 'Federal Government', 'Epic Games'],
      prefix: [],
      suffix: [],
      exampleT: ['I hate Apple'],
      exampleD: ['私はアップル社が嫌いです'],
      cf: ['grape', 'banana', 'facebook', 'twitter', 'instagram', 'huawei'],
    },
    '>pA|x-V<': {
      term: 'hippopotomonstrosesquipedaliophobia',
      definition: ['長い単語恐怖症'],
      synonym: [],
      antonym: ['short tale lover'],
      prefix: [],
      suffix: ['phobia'],
      exampleT: ['suffer from hippopotomonstrosesquipedaliophobia'],
      exampleD: ['長い単語恐怖症にさらされている'],
      cf: ['neophobia', 'technophobia', 'anthropophobia'],
    },
    lnz24x4C: {
      term: 'follow',
      definition: ['～（の後）に続く'],
      synonym: ['come after', 'go after', 'pursue'],
      antonym: ['lead', 'flout'],
      prefix: [],
      suffix: [],
      exampleT: ['Follow me home if you dare to.'],
      exampleD: ['あなたは彼に従うべきである'],
      cf: ['escort', 'attend'],
    },
    '6:LSsg9s': {
      term: 'consider',
      definition: ['～考慮する'],
      synonym: ['comtemplate', 'review'],
      antonym: ['ignore'],
      prefix: [],
      suffix: [],
      exampleT: ['all things considered'],
      exampleD: ['全ての事象を考慮した'],
      cf: [],
    },
  },
};

decksGeneral = {
  '7NCodht%}0': {
    title: 'Test Deck 1',
    user: 'WUgzMNtDDAap5TkAXZbrPwF97Bu2',
    language: { term: 'English', definition: 'Japanese' },
    thumbnail: {
      uri: 'photo-1515705576963-95cad62945b6?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8bWlsa3klMjB3YXl8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
      user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
    },
  },
  '-BiGIisZb*': {
    title: 'Test Deck 2',
    user: 'KgZLhZvgTiTSYJ7VBFbfutjjtUE2',
    language: { term: 'French', definition: 'Japanese' },
    thumbnail: {
      uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
      user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
    },
  },
  rUiKQdnLb9: {
    title: 'Test Deck 3',
    user: 'WUgzMNtDDAap5TkAXZbrPwF97Bu2',
    language: { term: 'Chinese', definition: 'Japanese' },
    thumbnail: {
      uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
      user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
    },
  },
  'xn>EfhY:2*': {
    title: 'Test Deck 4',
    user: 'KgZLhZvgTiTSYJ7VBFbfutjjtUE2',
    language: { term: 'Spanish', definition: 'Japanese' },
    thumbnail: {
      uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
      user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
    },
  },
  'Q38xR=rnKc': {
    title: 'Test Deck 5',
    user: 'WUgzMNtDDAap5TkAXZbrPwF97Bu2',
    language: { term: 'Korean', definition: 'Japanese' },
    thumbnail: {
      uri: 'photo-1574709057920-a44a16a9ab1a?ixlib=rb-1.2.1&q=…ysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzU4MX0',
      user: { link: 'https://unsplash.com/@tobias_markmeyer', name: 'Tobias Markmeyer' },
    },
  },
};
*/
